= nvim-lsp-installerの紹介
:author: hituzi no sippo
:revnumber: v1.3.0
:revdate: 2021-12-14T06:15:12+0900
:revremark: `LspInstallInfo` のUI内のhelpとUIを閉じるkeyが変更できない主旨の文を追加する
:description: Language Server Protocol(LSP)用のserverを \
              管理するNeovim用のpluignの紹介
:toc: preamble
// The meta attributes that are not built into Asciidoc.
// The `copyright` attribute is an attribute built into Asciidoctor.
:copyright: copyright (c) 2021 {author}
:creation_date: 2021-12-04T12:39:38+0900
:first_publication_date: 2021-12-05T18:05:02+0900
:tags: introduction, lsp, lsp installer, neovim, neovim plugin, lsp plugin
:nvim-lsp-installer_url: https://github.com/williamboman/nvim-lsp-installer
:nvim-lsp-installer_link: link:{nvim-lsp-installer_url}[nvim-lsp-installer^]

.Version
link:{nvim-lsp-installer_url}/commit/8fab72f68391a2719b5ee7b399789d33e0a2d416[
2021/12/5^]

.{nvim-lsp-installer_link}とは
Language Server Protocol(LSP)のserverをinstall,uninstallするNeovim用のpluginです。

[NOTE]
====
明記しない場合、serverとはLanguage Server Protocolのserverを指し示します。
====

.特徴
* 簡単にserverをinstallできる
  `LspInstall <server_name>` or `LspInstallInfo` で `i` keyを押す
* serverのversionを選択できる
  e.g. `LspInstall rust_analyzer@nightly`
* link:https://github.com/williamboman/nvim-lsp-installer/blob/main/CUSTOM_SERVERS.md[
  LSP server^]を追加できる
* serverの起動時間を早める最適化ができる
* Windowsのfull support

link:{nvim-lsp-installer_url}#available-lsps[
対応しているserverを知りたい人は、公式のREADMEを見てください。^]

== Commands

.管理
LspInstallInfo::
  installしているserverや、installできるserverをfloating windowで表示します。
  serverのinstall, uninstall, updateもできます。
  `?` keyを押せば、keymapのhelpを表示します。
+
--
[pass]
++++
<details><summary>LspInstallInfoで表示されるbuffer</summary>
++++

* ここだけnvim-lsp-installerのversionはlink:{nvim-lsp-installer_url}/commit/4d48eb45e76c64facdb1cea62f651a5e51ea33be[
  2021/12/13^]です。
* 中央揃えの部分は左に寄せています。
* iconやkeymapはdefaultから変更しています。

.serverの詳細情報表示&install/uninstall画面
[literal]
....
nvim-lsp-installer
  press ? for help
https://github.com/williamboman/nvim-lsp-installer

Installed servers (1)
  i sumneko_lua
    last updated this month
    filetypes    lua
    path         ~/.local/share/nvim/lsp_servers/sumneko_lua
    homepage     https://github.com/sumneko/lua-language-server

Available servers (74)
  x cmake
  x graphql
  x dotls
  # 長いので省略
  ...
  x zls
....

.help画面(`?` keyで表示される)
[literal]
....
:help nvim-lsp-installer
press ? for server list
https://github.com/williamboman/nvim-lsp-installer

Installer log: ~/.cache/nvim/lsp-installer.log

Keyboard shortcuts
Toggle help        ?
Toggle server info i
Update server      o
Uninstall server   x
Install server     a
Close window       <Esc>
Close window       q

Problems installing/uninstalling servers
Make sure you meet the minimum requirements to install servers. For debugging, refer to:
  :help nvim-lsp-installer-debugging
  :checkhealth nvim-lsp-installer

Problems with server functionality
Please refer to each language server's own homepage for further assistance.

> Current settings :help nvim-lsp-installer-settings

_______________________________________________________________________
< Help sponsor Neovim development! https://github.com/sponsors/neovim >
-----------------------------------------------------------------------
       \    ,-^-.
        \   !oYo!
         \ /./=\.\______
              ##        )\/\
               ||-----w||
               ||      ||

        Cowth Vader (alleged Neovim user)
....

[pass]
++++
</details>
++++
--
LspInstall [--sync] <server_name>::
  serverを(re)installします。
  serverは `<server_name>` で選択します。
  `--sync` を引数に渡したときはblocking方式でinstallし、
  installが終わるまで何もできません。
  `--sync` はscriptだけで使用するのを推奨しています。READMEに記載がありました。
LspUninstall [--sync] <server_name>::
  serverをuninstallします。
  他は `LspInstall` と同じです。
LspUninstall [--no-confirm]::
  Installしているserverを全てuninstallします。
  `--no-confirm` を引数に渡すと `(Y)es/(N)o` の確認をしません。

defaultのserverのinstall先は `stdpath("data")` になります。
`LspInstallInfo` でserverのinstall先を見られます。

[IMPORTANT]
====
installしただけでは、serverは動きません。
`setup()` functionを使用して、LSPのsetupをする必要があります。
====

.Log & Info
LspInstallLog::
  log fileを開きます。
  tabを生成し、そこに開きます。
LspPrintInstalled::
  installした全てのserverを表示します。

== Setup

.installしたserver全てを対象にしたsetup
[source, lua]
----
local lsp_installer = require("nvim-lsp-installer")

-- installしているserverの起動準備をします。
-- `server` に格納しているのはServer classで、
-- server nameやsetup functionを含んでいます。
lsp_installer.on_server_ready(function(server)
    local opts = {}

    -- `sumneko_lua` をinstallしているなら `hello world` を表示します。
    if server.name == 'sumneko_lua' then
      print('hello world')
    end

    -- serverに対応しているfiletypeのbufferを開いたら、
    -- 実行するfunctionを設定します。
    -- sumneko_luaはluaのLSP serverなので、
    -- luaのbufferを開いたら、実行するfunctionです。
    opts.on_attach = function(client,buffer_number)
      print(vim.inspect(client))
      print(buffer_number)
    end

    -- LSPのsetupをします。
    -- setupをしないとserverは動作しません。
    server:setup(opts)
end)
----

[NOTE]
====
`on_server_ready` をしなくても、serverを動かせます。

.これでもserverは動きます。
[source, lua]
----
local lsp_installer = require("nvim-lsp-installer")

-- installしているserverのdictを取得します。
local servers = lsp_installer.get_installed_servers()
-- serversの値はServer Classなので `setup` を実行できます。
servers[1]:setup({})
----

link:{nvim-lsp-installer_url}/blob/8fab72f68391a2719b5ee7b399789d33e0a2d416/lua/nvim-lsp-installer.lua#L215-L223[
`on_server_ready` のcode^]を読みましたが、
何をもって準備完了としているのか分かりませんでした。
====

.特定のserverを対象にしたsetup
[source, lua]
----
local lsp_installer_servers = require'nvim-lsp-installer.servers'

local name = 'sumneko_lua'
-- server_available
-- nvim-lsp-installerが対応しているserverかをbooleanで格納しています。
-- requested_server
-- serverが対応している場合、そのserverのLSPのdefault configが含まれている
-- Server class(`help nvim-lsp-installer.server`)を格納しています。
local server_available, requested_server = lsp_installer_servers.get_server(name)

-- nvim-lsp-installerに対応していないserverだったら、
-- error messageを表示して終了します。
if not server_available then
  error(string.format("nvim-lsp-installer doesn't support %s server.", name))
  return
end

requested_server:on_ready(function ()
  local opts = {}
  -- LSPのsetupをします。
  requested_server:setup(opts)
end)
-- serverがinstallされていない場合、installします。
if not requested_server:is_installed() then
  requested_server:install()
end
----

== `LspInstallInfo` のiconsとkeymap config

installしているserverや、installできるserverを表示する
`LspInstallInfo` のUIのconfig方法です。

.`LspInstallInfo` のUIのconfig(値はdefaultの値)
[source, lua]
----
local lsp_installer = require("nvim-lsp-installer")

lsp_installer.settings({
  ui = {
    icons = {
      -- installされたserverのicon
      server_installed = '◍',
      -- install待ちserverのicon
      server_pending = '◍',
      -- installしていないserverのicon
      server_uninstalled = '◍',
    },
    keymaps = {
      -- cursorのserverの詳細を表示するkey
      toggle_server_expand = '<CR>',
      -- cursorのserverをinstallするkey
      install_server = 'i',
      -- cursorのserverをupdateするkey
      update_server = 'u',
      -- cursorのserverをuninstallするkey
      uninstall_server = 'x',
    },
  },
})
----

[NOTE]
====
link:{nvim-lsp-installer_url}/blob/0fe8c254d90794f13860cbeac5e5987a081a8031/lua/nvim-lsp-installer/ui/status-win/init.lua#L9-L11[
2021/12/14の時点では、helpとUIを閉じるkeyを変更できません。^]
====

== Install Config

.installのconfig(値はdefaultの値)
[source, lua]
----
local lsp_installer = require("nvim-lsp-installer")
local path = require("nvim-lsp-installer.path")

lsp_installer.settings({
  -- install先のroot directory
  install_root_dir = path.concat { vim.fn.stdpath "data", "lsp_servers" },
  pip = {
      -- `pip install` に渡す引数
      -- 必要ない引数を渡すことは推奨されていません。
      -- 動作に影響を与える可能性が高いからです。
      -- e.g. `{ "--proxy", "https://proxyserver" }`
      install_args = {},
  },
  -- log level
  -- installに問題がありdebugする際、`vim.log.levels.DEBUG` にすると便利です。
  log_level = vim.log.levels.INFO,
  -- 同時にinstallできるserverの最大数
  max_concurrent_installers = 4,
})
----

== References

=== External

* {nvim-lsp-installer_link}


'''

// tag::license[]

:licensed-material-link: https://github.com/williamboman/nvim-lsp-installer/blob/main/README.md[nvim-lsp-installer/README.md^]
.{licensed-material-link}からの変更点
* 英語を日本語へ翻訳した
* 筆者がわかりやすいように説明を追加した
* 筆者が調査した内容を追加した

.link:https://github.com/williamboman/nvim-lsp-installer/blob/main/LICENSE[nvim-lsp-installer LICENSE^]
[%collapsible%open]
====

[literal]
....
                              Apache License
                        Version 2.0, January 2004
                     http://www.apache.org/licenses/

TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION

1. Definitions.

   "License" shall mean the terms and conditions for use, reproduction,
   and distribution as defined by Sections 1 through 9 of this document.

   "Licensor" shall mean the copyright owner or entity authorized by
   the copyright owner that is granting the License.

   "Legal Entity" shall mean the union of the acting entity and all
   other entities that control, are controlled by, or are under common
   control with that entity. For the purposes of this definition,
   "control" means (i) the power, direct or indirect, to cause the
   direction or management of such entity, whether by contract or
   otherwise, or (ii) ownership of fifty percent (50%) or more of the
   outstanding shares, or (iii) beneficial ownership of such entity.

   "You" (or "Your") shall mean an individual or Legal Entity
   exercising permissions granted by this License.

   "Source" form shall mean the preferred form for making modifications,
   including but not limited to software source code, documentation
   source, and configuration files.

   "Object" form shall mean any form resulting from mechanical
   transformation or translation of a Source form, including but
   not limited to compiled object code, generated documentation,
   and conversions to other media types.

   "Work" shall mean the work of authorship, whether in Source or
   Object form, made available under the License, as indicated by a
   copyright notice that is included in or attached to the work
   (an example is provided in the Appendix below).

   "Derivative Works" shall mean any work, whether in Source or Object
   form, that is based on (or derived from) the Work and for which the
   editorial revisions, annotations, elaborations, or other modifications
   represent, as a whole, an original work of authorship. For the purposes
   of this License, Derivative Works shall not include works that remain
   separable from, or merely link (or bind by name) to the interfaces of,
   the Work and Derivative Works thereof.

   "Contribution" shall mean any work of authorship, including
   the original version of the Work and any modifications or additions
   to that Work or Derivative Works thereof, that is intentionally
   submitted to Licensor for inclusion in the Work by the copyright owner
   or by an individual or Legal Entity authorized to submit on behalf of
   the copyright owner. For the purposes of this definition, "submitted"
   means any form of electronic, verbal, or written communication sent
   to the Licensor or its representatives, including but not limited to
   communication on electronic mailing lists, source code control systems,
   and issue tracking systems that are managed by, or on behalf of, the
   Licensor for the purpose of discussing and improving the Work, but
   excluding communication that is conspicuously marked or otherwise
   designated in writing by the copyright owner as "Not a Contribution."

   "Contributor" shall mean Licensor and any individual or Legal Entity
   on behalf of whom a Contribution has been received by Licensor and
   subsequently incorporated within the Work.

2. Grant of Copyright License. Subject to the terms and conditions of
   this License, each Contributor hereby grants to You a perpetual,
   worldwide, non-exclusive, no-charge, royalty-free, irrevocable
   copyright license to reproduce, prepare Derivative Works of,
   publicly display, publicly perform, sublicense, and distribute the
   Work and such Derivative Works in Source or Object form.

3. Grant of Patent License. Subject to the terms and conditions of
   this License, each Contributor hereby grants to You a perpetual,
   worldwide, non-exclusive, no-charge, royalty-free, irrevocable
   (except as stated in this section) patent license to make, have made,
   use, offer to sell, sell, import, and otherwise transfer the Work,
   where such license applies only to those patent claims licensable
   by such Contributor that are necessarily infringed by their
   Contribution(s) alone or by combination of their Contribution(s)
   with the Work to which such Contribution(s) was submitted. If You
   institute patent litigation against any entity (including a
   cross-claim or counterclaim in a lawsuit) alleging that the Work
   or a Contribution incorporated within the Work constitutes direct
   or contributory patent infringement, then any patent licenses
   granted to You under this License for that Work shall terminate
   as of the date such litigation is filed.

4. Redistribution. You may reproduce and distribute copies of the
   Work or Derivative Works thereof in any medium, with or without
   modifications, and in Source or Object form, provided that You
   meet the following conditions:

   (a) You must give any other recipients of the Work or
       Derivative Works a copy of this License; and

   (b) You must cause any modified files to carry prominent notices
       stating that You changed the files; and

   (c) You must retain, in the Source form of any Derivative Works
       that You distribute, all copyright, patent, trademark, and
       attribution notices from the Source form of the Work,
       excluding those notices that do not pertain to any part of
       the Derivative Works; and

   (d) If the Work includes a "NOTICE" text file as part of its
       distribution, then any Derivative Works that You distribute must
       include a readable copy of the attribution notices contained
       within such NOTICE file, excluding those notices that do not
       pertain to any part of the Derivative Works, in at least one
       of the following places: within a NOTICE text file distributed
       as part of the Derivative Works; within the Source form or
       documentation, if provided along with the Derivative Works; or,
       within a display generated by the Derivative Works, if and
       wherever such third-party notices normally appear. The contents
       of the NOTICE file are for informational purposes only and
       do not modify the License. You may add Your own attribution
       notices within Derivative Works that You distribute, alongside
       or as an addendum to the NOTICE text from the Work, provided
       that such additional attribution notices cannot be construed
       as modifying the License.

   You may add Your own copyright statement to Your modifications and
   may provide additional or different license terms and conditions
   for use, reproduction, or distribution of Your modifications, or
   for any such Derivative Works as a whole, provided Your use,
   reproduction, and distribution of the Work otherwise complies with
   the conditions stated in this License.

5. Submission of Contributions. Unless You explicitly state otherwise,
   any Contribution intentionally submitted for inclusion in the Work
   by You to the Licensor shall be under the terms and conditions of
   this License, without any additional terms or conditions.
   Notwithstanding the above, nothing herein shall supersede or modify
   the terms of any separate license agreement you may have executed
   with Licensor regarding such Contributions.

6. Trademarks. This License does not grant permission to use the trade
   names, trademarks, service marks, or product names of the Licensor,
   except as required for reasonable and customary use in describing the
   origin of the Work and reproducing the content of the NOTICE file.

7. Disclaimer of Warranty. Unless required by applicable law or
   agreed to in writing, Licensor provides the Work (and each
   Contributor provides its Contributions) on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
   implied, including, without limitation, any warranties or conditions
   of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A
   PARTICULAR PURPOSE. You are solely responsible for determining the
   appropriateness of using or redistributing the Work and assume any
   risks associated with Your exercise of permissions under this License.

8. Limitation of Liability. In no event and under no legal theory,
   whether in tort (including negligence), contract, or otherwise,
   unless required by applicable law (such as deliberate and grossly
   negligent acts) or agreed to in writing, shall any Contributor be
   liable to You for damages, including any direct, indirect, special,
   incidental, or consequential damages of any character arising as a
   result of this License or out of the use or inability to use the
   Work (including but not limited to damages for loss of goodwill,
   work stoppage, computer failure or malfunction, or any and all
   other commercial damages or losses), even if such Contributor
   has been advised of the possibility of such damages.

9. Accepting Warranty or Additional Liability. While redistributing
   the Work or Derivative Works thereof, You may choose to offer,
   and charge a fee for, acceptance of support, warranty, indemnity,
   or other liability obligations and/or rights consistent with this
   License. However, in accepting such obligations, You may act only
   on Your own behalf and on Your sole responsibility, not on behalf
   of any other Contributor, and only if You agree to indemnify,
   defend, and hold each Contributor harmless for any liability
   incurred by, or claims asserted against, such Contributor by reason
   of your accepting any such warranty or additional liability.

END OF TERMS AND CONDITIONS
....

====

// end::license[]
